# Generated by Django 5.2.7 on 2025-11-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_size_name'),
        ('users', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(default='temp_login', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_products', to='main.product'),
        ),
    ]
