# Generated by Django 5.2.7 on 2025-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_login_customuser_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
