# Generated by Django 5.2.7 on 2025-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
