# Generated by Django 5.2.7 on 2025-11-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='feed',
            field=models.BooleanField(default=False),
        ),
    ]
